dist: xenial

language: python
python:
  - "3.8"

services:
  - docker
jobs:
  include:
    - name: "Linter"
      before_script:
        - pip install -q flake8
      script:
        # Force Flake8 to use the exit status code 0 even if there are errors.
        # @TODO: remove '--exit-zero' once Python code has been cleaned up.
        - "flake8 --exit-zero"

    - name: "Django Test"
      before_script:
        - docker-compose -v
        - docker -v
        - docker-compose -f local.yml build
        # Ensure celerybeat does not crash due to non-existent tables
        - docker-compose -f local.yml run --rm django python manage.py migrate
        - docker-compose -f local.yml up -d
      script:
        - "docker-compose -f local.yml run django pytest"
      after_failure:
        - docker-compose -f local.yml logs
