# Generated by Django 2.2.6 on 2019-10-12 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack', '0003_auto_20191012_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='submitter',
            new_name='user',
        ),
    ]
