# Generated by Django 2.2.6 on 2019-10-19 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack', '0024_auto_20191019_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_end',
            field=models.TimeField(default=datetime.time(16, 0, 43, 391015)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_start',
            field=models.TimeField(default=datetime.time(10, 0, 43, 390979)),
        ),
        migrations.AlterField(
            model_name='paper',
            name='citation_txt',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='paper',
            name='description',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='paper',
            name='focus',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='paper',
            name='why',
            field=models.TextField(max_length=500),
        ),
    ]
