# Generated by Django 2.2.6 on 2019-10-19 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack', '0025_auto_20191019_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='consent_rescience',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='contact',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='feedback',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='public',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_end',
            field=models.TimeField(default=datetime.time(16, 0, 53, 229458)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_start',
            field=models.TimeField(default=datetime.time(10, 0, 53, 229425)),
        ),
    ]
