# Generated by Django 2.2.6 on 2019-10-20 11:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reprohack', '0026_auto_20191019_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='consent_rescience',
        ),
        migrations.AddField(
            model_name='paper',
            name='author_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paper',
            name='authorship',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_end',
            field=models.TimeField(default=datetime.time(16, 0, 7, 484769)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_start',
            field=models.TimeField(default=datetime.time(10, 0, 7, 484738)),
        ),
        migrations.AlterField(
            model_name='paper',
            name='citation_txt',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='paper',
            name='contact',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='feedback',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='focus',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='paper',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='why',
            field=models.TextField(max_length=400),
        ),
    ]
