# Generated by Django 2.2.6 on 2019-10-20 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack', '0027_auto_20191020_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='feedback',
        ),
        migrations.AlterField(
            model_name='event',
            name='time_end',
            field=models.TimeField(default=datetime.time(16, 0, 0, 475744)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_start',
            field=models.TimeField(default=datetime.time(10, 0, 0, 475697)),
        ),
    ]
