# Generated by Django 2.2.6 on 2019-10-21 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack', '0030_auto_20191021_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_end',
            field=models.TimeField(default=datetime.time(16, 0, 27, 398303)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_start',
            field=models.TimeField(default=datetime.time(10, 0, 27, 398273)),
        ),
        migrations.AlterField(
            model_name='paper',
            name='authorship',
            field=models.BooleanField(default=True),
        ),
    ]
