# Generated by Django 2.2.6 on 2019-10-22 18:59

import datetime
import django.contrib.gis.geos.point
from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack', '0035_auto_20191022_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='geom',
            field=djgeojson.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_end',
            field=models.TimeField(default=datetime.time(16, 0, 18, 787256)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_start',
            field=models.TimeField(default=datetime.time(10, 0, 18, 787223)),
        ),
    ]
