# Generated by Django 3.0.7 on 2020-07-23 21:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Event title', max_length=200)),
                ('citation_txt', models.TextField(max_length=300)),
                ('doi', models.CharField(default='10.1000/xyz123', max_length=200)),
                ('description', models.TextField(max_length=400)),
                ('why', models.TextField(max_length=400)),
                ('focus', models.TextField(max_length=400)),
                ('paper_url', models.URLField()),
                ('code_url', models.URLField()),
                ('data_url', models.URLField()),
                ('extra_url', models.URLField()),
                ('citation_bib', models.CharField(max_length=800)),
                ('authorship', models.BooleanField(default=True)),
                ('contact', models.BooleanField(default=True)),
                ('public', models.BooleanField(default=True)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tools', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(through='reprohack.Membership', to=settings.AUTH_USER_MODEL)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reprohack.Paper')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='report_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reprohack.ReportGroup'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=200)),
                ('title', models.CharField(default='Event title', max_length=200)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time_start', models.TimeField(default=datetime.time(10, 0, 26, 123733))),
                ('time_end', models.TimeField(default=datetime.time(16, 0, 26, 123778))),
                ('location', models.CharField(default='', max_length=200)),
                ('address1', models.CharField(default='', max_length=200)),
                ('address2', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=60)),
                ('postcode', models.CharField(default='', max_length=15)),
                ('country', models.CharField(default='', max_length=60)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('registration_url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
