# Generated by Django 3.0.7 on 2020-08-08 14:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
