# Generated by Django 3.0.7 on 2020-08-08 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reprohack', '0002_auto_20200808_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='authorship',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='submitter',
        ),
        migrations.CreateModel(
            name='AuthorsAndSubmitters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.BooleanField(default=True)),
                ('author', models.BooleanField(default=True)),
                ('submitted', models.BooleanField(default=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reprohack.Paper')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='authors_and_submitters',
            field=models.ManyToManyField(through='reprohack.AuthorsAndSubmitters', to=settings.AUTH_USER_MODEL),
        ),
    ]
