# Generated by Django 3.0.7 on 2020-08-08 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack', '0004_auto_20200808_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperreviewer',
            old_name='lead_review',
            new_name='lead_reviewer',
        ),
        migrations.AddField(
            model_name='review',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
