# Generated by Django 3.0.7 on 2020-08-09 19:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack', '0005_auto_20200808_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='documentation',
        ),
        migrations.RemoveField(
            model_name='review',
            name='method_familiarity',
        ),
        migrations.RemoveField(
            model_name='review',
            name='method_reusability',
        ),
        migrations.AddField(
            model_name='review',
            name='method_familiarity_rating',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='After attempting to reproduce, how familiar do you feel with the code and methods used in the paper?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='method_reusability_rating',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Rate the project on reusability of the material.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='transparency_suggestions',
            field=markdownx.models.MarkdownxField(default=5, verbose_name='Any suggestions on how the analysis could be made more transparent?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paper',
            name='doi',
            field=models.CharField(max_length=200, verbose_name='DOI (eg: 10.1000/xyz123)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='advantages',
            field=markdownx.models.MarkdownxField(verbose_name='What were the positive features of this approach?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='challenges',
            field=markdownx.models.MarkdownxField(verbose_name='What were the main challenges you ran into (if any)?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='code_permissive_license',
            field=models.BooleanField(verbose_name='Permissive license for CODE included'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comments_and_suggestions',
            field=markdownx.models.MarkdownxField(verbose_name='Any other comments/suggestions on the reproducibility approach?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='data_permissive_license',
            field=models.BooleanField(verbose_name='Permissive license for DATA included'),
        ),
        migrations.AlterField(
            model_name='review',
            name='documentation_cons',
            field=markdownx.models.MarkdownxField(verbose_name='How could the documentation be improved?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='documentation_pros',
            field=markdownx.models.MarkdownxField(verbose_name='What do you like about the documentation?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='documentation_rating',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='How well was the material documented?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reprohack.Event'),
        ),
        migrations.AlterField(
            model_name='review',
            name='familiarity_with_method',
            field=markdownx.models.MarkdownxField(verbose_name='Briefly describe your familiarity with the procedure/tools used by the paper.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='general_comments',
            field=models.TextField(verbose_name='Any final comments:'),
        ),
        migrations.AlterField(
            model_name='review',
            name='operating_system',
            field=models.CharField(choices=[('linux', 'Linux/FreeBSD or other Open Source Operating system'), ('macOS', 'Apple Operating System'), ('windows', 'Windows Operating System')], max_length=7, verbose_name='Which type of operating system were you working in?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='operating_system_detail',
            field=models.CharField(max_length=100, verbose_name='What operating system were you using eg: Ubuntu 14.04.6 LTS, macOS 10.15 or Windows 10 Pro? '),
        ),
        migrations.AlterField(
            model_name='review',
            name='reproducibility_description',
            field=markdownx.models.MarkdownxField(default='', verbose_name='Briefly describe the procedure followed/toolsused to reproduce it.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='reproducibility_outcome',
            field=models.CharField(choices=[('y', 'Fully Reproducible'), ('p', 'Partially Reproducible'), ('n', 'Not Reproducible')], default='n', max_length=1, verbose_name='Did you manage to reproduce it?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reproducibility_rating',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='On a scale of 1 to 10, how much of the paper did you manage to reproduce?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reusability_suggestions',
            field=models.TextField(verbose_name='Any suggestions on how the project could be more reusable?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='software_installed',
            field=markdownx.models.MarkdownxField(verbose_name='What additional software did you need to install?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='software_used',
            field=markdownx.models.MarkdownxField(verbose_name='What software did you use?'),
        ),
    ]
