# Generated by Django 3.0.7 on 2020-08-09 23:07

from django.db import migrations, models
import reprohack_hub.reprohack.models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack', '0008_auto_20200809_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=reprohack_hub.reprohack.models.default_event_end),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=reprohack_hub.reprohack.models.default_event_start),
        ),
    ]
