# Generated by Django 3.0.7 on 2020-08-10 00:55

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack', '0009_auto_20200809_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
