# Generated by Django 3.0.7 on 2020-08-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack', '0010_auto_20200810_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
