# Generated by Django 2.2.8 on 2020-06-05 18:39

import datetime
from django.db import migrations, models
import django.utils.timezone
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=200)),
                ('title', models.CharField(default='Event title', max_length=200)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time_start', models.TimeField(default=datetime.time(10, 0, 14, 683784))),
                ('time_end', models.TimeField(default=datetime.time(16, 0, 14, 683823))),
                ('location', models.CharField(default='', max_length=200)),
                ('address1', models.CharField(default='', max_length=200)),
                ('address2', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=60)),
                ('postcode', models.CharField(default='', max_length=15)),
                ('country', models.CharField(default='', max_length=60)),
                ('geom', djgeojson.fields.PointField(blank=True)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('registration_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='Event title', max_length=200)),
                ('citation_txt', models.TextField(max_length=300)),
                ('doi', models.CharField(default='10.1000/xyz123', max_length=200)),
                ('description', models.TextField(max_length=400)),
                ('why', models.TextField(max_length=400)),
                ('focus', models.TextField(max_length=400)),
                ('paper_url', models.URLField()),
                ('code_url', models.URLField()),
                ('data_url', models.URLField()),
                ('extra_url', models.URLField()),
                ('citation_bib', models.CharField(max_length=800)),
                ('authorship', models.BooleanField(default=True)),
                ('contact', models.BooleanField(default=True)),
                ('public', models.BooleanField(default=True)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ReportGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UnregisteredAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
