# Generated by Django 3.1.4 on 2021-06-03 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='available',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='public',
        ),
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.TextField(default='test', verbose_name='Authors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='review_availability',
            field=models.CharField(choices=[('ALL', 'Allowed for reviews in any events'), ('EVT_ONLY', 'Only allowed to review for associated event'), ('ARCHIVE', 'Archive the paper, reviews are not allowed')], default='ALL', max_length=20, verbose_name='Paper review permissions'),
        ),
        migrations.AddField(
            model_name='paper',
            name='submitter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
