# Generated by Django 3.1.4 on 2021-04-27 12:19

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='geom',
            field=djgeojson.fields.PointField(blank=True, null=True),
        ),
    ]
