# Generated by Django 3.1.4 on 2021-06-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0002_auto_20210603_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='review_availability',
            field=models.CharField(choices=[('ALL', 'Allowed for reviews in any events'), ('EVT_ONLY', 'Only allowed to review for associated event'), ('ARCHIVE', 'Archive the paper, reviews are not allowed')], default='ALL', max_length=20, verbose_name='Paper review permission'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.TextField(verbose_name='Paper Title'),
        ),
    ]
