# Generated by Django 3.1.4 on 2021-04-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0002_event_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
