# Generated by Django 3.1.4 on 2021-06-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0004_paper_review_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='review_public',
            new_name='public_reviews',
        ),
    ]
