# Generated by Django 3.1.4 on 2021-05-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0004_remove_paper_authors_and_submitters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='geom',
        ),
        migrations.AddField(
            model_name='event',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
