# Generated by Django 3.1.4 on 2021-05-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0005_auto_20210506_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='event',
            name='long',
        ),
        migrations.AddField(
            model_name='event',
            name='event_coordinates',
            field=models.TextField(blank=True, null=True),
        ),
    ]
