# Generated by Django 3.1.4 on 2021-06-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0005_auto_20210603_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='email_review',
            field=models.BooleanField(default=True, verbose_name='Send me an email when a review is received'),
        ),
    ]
