# Generated by Django 3.1.4 on 2021-06-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0006_paper_email_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='public_review',
            field=models.BooleanField(default=True, verbose_name='Allow this review to be made public'),
        ),
    ]
