# Generated by Django 3.1.4 on 2021-07-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0008_auto_20210719_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='tools',
            new_name='tags',
        ),
    ]
