# Generated by Django 3.1.4 on 2021-09-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0010_auto_20210806_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='citation_bib',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='data_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='doi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='DOI (eg. 10.1000/xyz123)'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='extra_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
