# Generated by Django 3.1.4 on 2021-09-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0011_auto_20210907_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='citation_bib',
            field=models.TextField(blank=True, null=True, verbose_name='BibTex reference: paper reference in BibTex format'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='citation_txt',
            field=models.TextField(max_length=300, verbose_name='Citation: full citation of the paper as text'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='description',
            field=models.TextField(max_length=400, verbose_name='Short Description of the paper'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='focus',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='What should reviewers focus on?'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='why',
            field=models.TextField(max_length=400, verbose_name='Why someone attempt to reproduce this paper?'),
        ),
    ]
