# Generated by Django 3.1.4 on 2021-09-08 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0013_auto_20210907_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
