# Generated by Django 3.1.4 on 2021-09-09 14:35

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('reprohack_hub', '0015_auto_20210908_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.TextField(help_text='Please separate authors names with commas', verbose_name='Paper Authors'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='citation_bib',
            field=models.TextField(blank=True, help_text='BibTeX Format Paper Description', null=True, verbose_name='BibTex Paper reference'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='citation_txt',
            field=models.TextField(help_text='Full reference of the paper in text format', max_length=1000, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='code_url',
            field=models.URLField(help_text='If all materials are present in a single repository, provide the URL here.', verbose_name='Code or Repository URL'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='data_url',
            field=models.URLField(blank=True, help_text='Optional', null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='description',
            field=models.TextField(help_text='Include a description of analysis and reproducibility approach (e.g. programming language etc)', max_length=2000, verbose_name='Short Description of the paper'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Associated Event (leave blank if general submission)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reprohack_hub.event'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='extra_url',
            field=models.URLField(blank=True, help_text='Optional', null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='focus',
            field=models.TextField(blank=True, help_text='Optional. Use to point reviewers to specific difficulties or particular areas you want feedback on', max_length=1000, null=True, verbose_name='What should reviewers focus on?'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_url',
            field=models.URLField(help_text='Ideally to an Open Access version of your paper', verbose_name='Paper URL'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='public_reviews',
            field=models.BooleanField(default=True, help_text='Only reviews that have also been set to public by reviewers will be visible to others', verbose_name='Make reviews public'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Help make your papers findable through a search. Include tags of the reserach domain, programming languages used or any other relevant tools (e.g. Docker, HPC)', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='why',
            field=models.TextField(help_text='Help motivate potential reviewers to select your paper!', max_length=2000, verbose_name='Why someone attempt to reproduce this paper?'),
        ),
    ]
