# Generated by Django 3.1.4 on 2021-09-10 14:12

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0017_auto_20210909_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='advantages',
            field=markdownx.models.MarkdownxField(verbose_name='What were the positive features of this approach?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='challenges',
            field=markdownx.models.MarkdownxField(verbose_name='What were the main challenges you ran into (if any)?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comments_and_suggestions',
            field=markdownx.models.MarkdownxField(blank=True, default='', verbose_name='Any other comments/suggestions on the reproducibility approach?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='documentation_cons',
            field=markdownx.models.MarkdownxField(verbose_name='How could the documentation be improved?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='documentation_pros',
            field=markdownx.models.MarkdownxField(verbose_name='What do you like about the documentation?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Is the review associated with an Event? (leave blank if not)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reprohack_hub.event'),
        ),
        migrations.AlterField(
            model_name='review',
            name='familiarity_with_method',
            field=markdownx.models.MarkdownxField(help_text='Markdown field', verbose_name='Briefly describe your familiarity with the procedure/tools used by the paper.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='general_comments',
            field=markdownx.models.MarkdownxField(blank=True, default='', verbose_name='Any final comments?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='public_review',
            field=models.BooleanField(default=True, help_text='Only reviews on papers that have also been set to receive public reviews by authors will be visible to others', verbose_name='Allow this review to be made public'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reproducibility_description',
            field=markdownx.models.MarkdownxField(help_text='Markdown field', verbose_name='Briefly describe the procedure followed/tools used to reproduce it.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reusability_suggestions',
            field=markdownx.models.MarkdownxField(blank=True, default='', verbose_name='Any suggestions on how the project could be more reusable?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='software_installed',
            field=markdownx.models.MarkdownxField(verbose_name='What additional software did you need to install?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='software_used',
            field=markdownx.models.MarkdownxField(verbose_name='What software did you use?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='transparency_suggestions',
            field=markdownx.models.MarkdownxField(blank=True, default='', verbose_name='Any suggestions on how the analysis could be made more transparent?'),
        ),
    ]
