# Generated by Django 3.1.4 on 2021-09-10 15:43

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0018_auto_20210910_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='advantages',
            field=markdownx.models.MarkdownxField(help_text='Markdown field', verbose_name='What were the positive features of this approach?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='challenges',
            field=markdownx.models.MarkdownxField(help_text='Markdown field', verbose_name='What were the main challenges you ran into (if any)?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comments_and_suggestions',
            field=markdownx.models.MarkdownxField(blank=True, default='', help_text='Markdown field', verbose_name='Any other comments/suggestions on the reproducibility approach?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='documentation_cons',
            field=markdownx.models.MarkdownxField(help_text='Markdown field', verbose_name='How could the documentation be improved?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='documentation_pros',
            field=markdownx.models.MarkdownxField(help_text='Markdown field', verbose_name='What do you like about the documentation?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='general_comments',
            field=markdownx.models.MarkdownxField(blank=True, default='', help_text='Markdown field', verbose_name='Any final comments?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reusability_suggestions',
            field=markdownx.models.MarkdownxField(blank=True, default='', help_text='Markdown field', verbose_name='Any suggestions on how the project could be more reusable?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='software_installed',
            field=markdownx.models.MarkdownxField(help_text='Markdown field', verbose_name='What additional software did you need to install?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='software_used',
            field=markdownx.models.MarkdownxField(help_text='Markdown field', verbose_name='What software did you use?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='transparency_suggestions',
            field=markdownx.models.MarkdownxField(blank=True, default='', help_text='Markdown field', verbose_name='Any suggestions on how the analysis could be made more transparent?'),
        ),
    ]
