# Generated by Django 3.1.4 on 2021-09-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0020_auto_20210923_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='creator',
            new_name='user',
        ),
    ]
