# Generated by Django 3.1.4 on 2021-09-23 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0021_auto_20210923_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='creator',
        ),
    ]
