# Generated by Django 3.1.4 on 2021-09-29 14:31

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0023_event_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='address1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='event',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='postcode',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
