# Generated by Django 3.1.4 on 2021-09-29 16:37

from django.db import migrations, models
import markdownx.models
import reprohack_hub.models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0024_auto_20210929_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hackpad_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=markdownx.models.MarkdownxField(default=reprohack_hub.models.get_default_description, verbose_name='Feel free to customise provided template'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_url',
            field=models.URLField(blank=True),
        ),
    ]
