# Generated by Django 3.1.4 on 2021-10-02 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0026_auto_20210930_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='why',
            field=models.TextField(help_text='Help motivate potential reviewers to select your paper!', max_length=2000, verbose_name='Why should someone attempt to reproduce this paper?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='documentation_rating',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='How well was the material documented?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='method_familiarity_rating',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='After attempting to reproduce, how familiar do you feel with the code and methods used in the paper?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='method_reusability_rating',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Rate the project on reusability of the material.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reproducibility_outcome',
            field=models.CharField(choices=[('y', 'Fully Reproducible'), ('p', 'Partially Reproducible'), ('n', 'Not Reproducible')], default='y', max_length=1, verbose_name='Did you manage to reproduce it?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reproducibility_rating',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='How much of the paper did you manage to reproduce?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True, verbose_name='E-mail'),
        ),
    ]
