# Generated by Django 3.1.4 on 2021-10-04 16:12

from django.db import migrations, models
import django.db.models.deletion
import reprohack_hub.models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0028_auto_20211004_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Associated Event (leave blank if general submission)', limit_choices_to=reprohack_hub.models.limit_paper_event_choices, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reprohack_hub.event'),
        ),
    ]
