# Generated by Django 3.1.4 on 2021-10-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0030_auto_20211004_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Your full name'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_name',
            field=models.CharField(max_length=255, null=True, verbose_name='What should we call you?'),
        ),
    ]
