# Generated by Django 3.1.4 on 2021-10-07 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0031_auto_20211005_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperreviewer',
            name='lead_reviewer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paperreviewer',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reprohack_hub.review'),
        ),
        migrations.AlterField(
            model_name='paperreviewer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
