# Generated by Django 3.1.4 on 2021-10-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0035_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='email_comment',
            field=models.BooleanField(default=True, verbose_name='Send me an email when a comment is posted to a review of my paper'),
        ),
        migrations.AddField(
            model_name='review',
            name='email_comment',
            field=models.BooleanField(default=True, verbose_name='Send an email to reviewers when a comment is posted to this review'),
        ),
    ]
