# Generated by Django 3.1.4 on 2021-10-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0036_auto_20211011_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='operating_system_detail',
            field=models.CharField(blank=True, max_length=100, verbose_name='What operating system were you using (eg. Ubuntu 14.04.6 LTS, macOS 10.15 or Windows 10 Pro)?'),
        ),
    ]
