# Generated by Django 3.1.4 on 2021-10-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0037_auto_20211011_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='I have read and accept the Data Protection & Privacy Policy'),
        ),
    ]
