# Generated by Django 3.1.4 on 2021-10-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0038_user_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='orcid',
            field=models.CharField(blank=True, max_length=19),
        ),
    ]
