# Generated by Django 3.1.4 on 2021-11-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0039_auto_20211018_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='public_reviews',
            field=models.BooleanField(default=True, help_text='Only reviews that have also been set to public by reviewers will be visible publicly', verbose_name='Make reviews public'),
        ),
        migrations.AlterField(
            model_name='review',
            name='public_review',
            field=models.BooleanField(default=True, help_text='Only reviews on papers that have also been set to receive public reviews by authors will be visible publicly', verbose_name='Allow this review to be made public'),
        ),
    ]
