# Generated by Django 3.1.4 on 2021-12-01 13:40

from django.db import migrations, models
import markdownx.models
import reprohack_hub.models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0040_auto_20211129_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slides_url',
            field=models.URLField(blank=True, help_text="See our hackmd.io <a href='/intro_slides_template'> Introductory Slides Template</a>"),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=markdownx.models.MarkdownxField(default=reprohack_hub.models.get_default_description, help_text="Markdown field. See <a href='https://daringfireball.net/projects/markdown/syntax'> full documentation of supported syntax</a>", verbose_name='Feel free to customise provided template'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hackpad_url',
            field=models.URLField(blank=True, help_text="See our hackmd.io <a href='/hackpad_template'> Event Hackpad Template</a>"),
        ),
    ]
