# Generated by Django 3.1.4 on 2022-03-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reprohack_hub', '0041_auto_20211201_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='operating_system',
            field=models.CharField(choices=[('linux', 'Linux/FreeBSD or other Open Source Operating system'), ('macOS', 'Apple Operating System (macOSX)'), ('windows', 'Windows Operating System'), ('HPC', 'High Performance Computing Cluster'), ('Cloud', 'Cloud Computing')], max_length=7, verbose_name='Which type of operating system were you working in?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='operating_system_detail',
            field=models.CharField(blank=True, max_length=100, verbose_name='What operating system were you using (eg. Ubuntu 14.04.6 LTS, macOS 10.15 or Windows 10 Pro, Sulis HPC Framework)?'),
        ),
    ]
